### ISSUE TITLE
Einfache Implemtierung des Wissensportals

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#389]

**Comment by friedrichweise** [comment]
Das `area` würde ich nicht mit als Attribut in der UI aufnehmen. Das sollte die API wegabstrahieren.

**Comment by friedrichweise** [comment]
### Todos UI
- [ ] Anzeigen Anzahl Kapitel in Sidebar

**Comment by friedrichweise** [comment]
### Todos API
- [ ] Branch `dev-guide` aus `afeefa-backend-api` entfernen, da wir einen getrennten service entwickeln

**Comment by friedrichweise** [comment]
Wir müssen nochmal über die API Spezifikation sprechen. Unsere `api.js` Datei fordert gerade noh ein `data` und ein `type` Attribut.

**Comment by friedrichweise** [comment]
@kakenbok Gibt es irgendwelche Änderungen in der API, die ich noch nicht mitbekommen habe? Ich habe die zwei API's und die UI (alle im Branch `dev-guide`) gestartet. Leider kommen ständig fehler beim `deserialize()`:

**Comment by friedrichweise** [comment]
Okay. Problem lag an einem kleinem Git-Durcheinander. Folgende Repos müssen in folgenden Branches gestartet werden:
__backend-ui__: `dev-guide`
__backend-api__: `dev-chapters`
__wisdom-api__: `master`

**Comment by friedrichweise** [comment]
Todos:
- [ ] Anzahl ins `meta`Request packen
- [ ] Erstelllen von Kapiteln
- [ ] Icon in Listenansicht entfernen
- [ ] Detailview entfernen -> direkt zum Bearbeiten

**Comment by friedrichweise** [comment]
Mittlerweile ist alles in den `dev`-Branch gemerged.

**Comment by friedrichweise** [comment]
Der Vorschaulink ist als Button im Header implementiert. Jedoch kann es hier zu Verwechslungen kommen: Der Redakteur erwartet nach Eingabe von Text im Editor eine **Vorschau** des geschriebenen Text. Dabei kann der Link nur gespeicherte Kapitel im Frontend anzeigen. Somit ist **Vorschau** vielleicht das falsche Wort.

**Comment by stevereinke** [comment]
noch offen in backend api: chapter configuration, branch mit begonnener implementierung bereits verfübar
